events {}
 
http {
    upstream spring_backend {
        server spring-service-1:8900;
        server spring-service-2:8900;
    }
 
    server {
        listen 80;
        location / {
        proxy_pass http://spring_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}