spring.application.name=trace-project-service


spring.data.mongodb.uri= mongodb://root:root@my-mongodb.database.svc.cluster.local:27017/cicd_db

# Resilience4j Retry configuration in application.properties

resilience4j.retry.instances.createProjectRetry.maxAttempts=3
resilience4j.retry.instances.createProjectRetry.waitDuration=300ms
resilience4j.retry.instances.createProjectRetry.enableExponentialBackoff=true
resilience4j.retry.instances.createProjectRetry.exponentialBackoffMultiplier=2.0
resilience4j.retry.instances.createProjectRetry.enableRandomizedWait=true
# Exceptions to ignore
resilience4j.retry.instances.createProjectRetry.ignoreExceptions=org.springframework.web.client.HttpClientErrorException$BadRequest


resilience4j.retry.instances.createProjectRetry.retryExceptions= java.lang.RuntimeException,java.net.SocketTimeoutException, org.springframework.web.client.HttpServerErrorException,org.springframework.web.client.ResourceAccessException
logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.core=DEBUG
logging.level.io.github.resilience4j=DEBUG

server.port=8081

# Actuator exposure (optional but useful)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Disable OTLP to avoid the micrometer connection refused noise (unless you run an OTEL collector)
management.otlp.metrics.export.enabled=true


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost