events {}
 
http {
    upstream detect_backend {
        server app-service-1:8088 weight=5;
        server app-service-2:8088 weight=5;
    
    }
 
    server {
        listen 80;
        location / {
        proxy_pass http://detect_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}