sonar.projectKey=trace-task-service
sonar.projectName=trace-task-service
sonar.host.url=http://localhost:9000
sonar.login=sqp_9f50302beb96586e9e0ea2722d73c53050258d71
sonar.token=sqp_9f50302beb96586e9e0ea2722d73c53050258d71
sonar.sources=src
sonar.java.binaries=target