export const getQuestionRequest = {
  GET_QUESTION: "GET_QUESTION",
  FILTER_BY_LANGUAGE: "FILTER_BY_LANGUAGE",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_LEVEL: "FILTER_BY_LEVEL",
  GET_CODE_ASSESSMENT_QUESTION: "GET_CODE_ASSESSMENT_QUESTION",
  RESET_CODE_ASSESSMENT_QUESTION:"RESET_CODE_ASSESSMENT_QUESTION",
};
