spring.application.name=task-service

spring.data.mongodb.uri=mongodb://root:jLGwIfQEv1@mongo-mongodb.database.svc.cluster.local:27017/employee_db?authSource=admin

server.port=8083

spring.data.redis.host=redis.database.svc.cluster.local
spring.data.redis.port=6379

spring.cache.type=redis