const GET_ALL_KNOWLEDGE_QUESTIONS = "/learning/getQuestions";
const GET_ALL_KNOWLEDGE_CORRECT_OPTIONS = "/learning/getAnswers";
const GET_ALL_KNOWLEDGE_TOPICS = "/learning/topic";
const ADD_KNOWLEDGE_TOPICS = "/learning/topic";
const ADD_KNOWLEDGE_SUBTOPICS = "/learning/subtopic";
const GET_ALL_KNOWLEDGE_SUBTOPICS = "/learning/subtopic";
const GET_ALL_KNOWLEDGE_QUESTION_BY_ID = "/learning/getSpecificQuestion";
const FILTER_KNOWLEDGE_QUESTIONS_TOPICS = "/learning/filterquestions";
const ADD_KNOWLEDGE_ASSESSMENT_BULK_QUESTION = "/learning/spreadsheet";
const GET_ALL_KNOWLEDGE_ASSESSMENT_QUESTIONS_BY_ID_AND_TYPE =
  "/learning/getAssessmentQuestions";
const ADD_COMPLETION_STATUS = "/learning/evaluate/status";
const EVALUATE_KNOWLEDGE_ASSESSMENT_MARK = "/learning/evaluate";
const DELETE_KNOWLEDGE_ASSESSMENT_SINGLE_QUESTION_BY_ID =
  "/learning/deleteAnswer";

//Detailed Report for User
const FETCH_ASSESSMENT_REPORT_BY_SCHEDULING_ID = "/learning/assessmentReport";
const FETCH_SCORE_CARD_DETAILS_BY_SCHEDULING_ID = "/learning/scorecardDetails";

const CHANGE_STATUS_KNOWLEDGE_QUESTION = "/learning/question/status";
const ACTION_KNOWLEDGE_QUESTION = "/learning/question";

const DETAILED_REPORT_GETASSESSMENT_NAME = "/learning/scheduleReport";
const DETAILED_REPORT_GET_USERS = "/user";
const LEARNING_ASSESSMENT_REPORT = "/learning/assessmentReport";
export {
  GET_ALL_KNOWLEDGE_QUESTIONS,
  GET_ALL_KNOWLEDGE_CORRECT_OPTIONS,
  GET_ALL_KNOWLEDGE_TOPICS,
  ADD_KNOWLEDGE_TOPICS,
  GET_ALL_KNOWLEDGE_QUESTION_BY_ID,
  FILTER_KNOWLEDGE_QUESTIONS_TOPICS,
  CHANGE_STATUS_KNOWLEDGE_QUESTION,
  ACTION_KNOWLEDGE_QUESTION,
  ADD_COMPLETION_STATUS,
  ADD_KNOWLEDGE_SUBTOPICS,
  GET_ALL_KNOWLEDGE_SUBTOPICS,
  ADD_KNOWLEDGE_ASSESSMENT_BULK_QUESTION,
  GET_ALL_KNOWLEDGE_ASSESSMENT_QUESTIONS_BY_ID_AND_TYPE,
  EVALUATE_KNOWLEDGE_ASSESSMENT_MARK,
  DELETE_KNOWLEDGE_ASSESSMENT_SINGLE_QUESTION_BY_ID,
  FETCH_ASSESSMENT_REPORT_BY_SCHEDULING_ID,
  FETCH_SCORE_CARD_DETAILS_BY_SCHEDULING_ID,
  DETAILED_REPORT_GETASSESSMENT_NAME,
  DETAILED_REPORT_GET_USERS,
  LEARNING_ASSESSMENT_REPORT,
};
