# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detect.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65tect.proto\x12\x06\x64\x65tect\"\x1a\n\x0bTestRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0cTestResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\"\n\x0f\x45venListRequest\x12\x0f\n\x07numList\x18\x01 \x03(\x05\"$\n\x10\x45venListResponse\x12\x10\n\x08\x65venList\x18\x01 \x03(\x05\x32\x8c\x01\n\rDetectService\x12\x37\n\nTestMethod\x12\x13.detect.TestRequest\x1a\x14.detect.TestResponse\x12\x42\n\rcalculateEven\x12\x17.detect.EvenListRequest\x1a\x18.detect.EvenListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTREQUEST']._serialized_start=24
  _globals['_TESTREQUEST']._serialized_end=50
  _globals['_TESTRESPONSE']._serialized_start=52
  _globals['_TESTRESPONSE']._serialized_end=79
  _globals['_EVENLISTREQUEST']._serialized_start=81
  _globals['_EVENLISTREQUEST']._serialized_end=115
  _globals['_EVENLISTRESPONSE']._serialized_start=117
  _globals['_EVENLISTRESPONSE']._serialized_end=153
  _globals['_DETECTSERVICE']._serialized_start=156
  _globals['_DETECTSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
