sonar.projectKey=trace-project-service
sonar.projectName=trace-project-service
sonar.host.url=http://localhost:9000
sonar.login=sqp_cc96d235b2c5f66c97787119e6c131ce23970f99
sonar.token=sqp_cc96d235b2c5f66c97787119e6c131ce23970f99
sonar.sources=src
sonar.java.binaries=target