const ADD_CODING_QUESTION_URL = "/question";
const UPDATE_CODING_QUESTION_URL = "/question";
const DELETE_CODING_QUESTION_URL = "/question?questionId=";
const GET_CODING_QUESTION_URL = "/question/";
const GET_ALL_CODING_QUESTION_URL = "/question";

const GET_ALL_LANGUAGE_URL = "/language";
const ADD_LANGUAGE_URL = "/language";

const GET_ALL_CATEGORY = "/category";
const ADD_CATEGORY_URL = "/category";

const REFERENCE_DOCUMENT_URL = "/downloadzipfile";

const QUESTION_FILTER_BY_LANGUAGE = "/filter";
const QUESTION_FILTER_BY_CATEGORY = "/filter";
const QUESTION_FILTER_BY_LEVEL = "/filter";
const FETCH_QUESTION_BY_ID = "/questions";
const CODE_ASSESSMENT_QUESTION = "/attempt";
const MAP_CODING_QUESTION = "/attempt";
const RUN_CODE = "/attempt";
const CUSTOM_RUN_CODE = "/attempt/custom";
const SUBMIT_CODE = "/attempt";
const GET_SKILL_REPORT = "/attempt";

const GET_SKILL_RESULT = "/result";

const SKILL_BASE_URL = "/skill";
export {
  ADD_CATEGORY_URL,
  ADD_CODING_QUESTION_URL,
  ADD_LANGUAGE_URL,
  CODE_ASSESSMENT_QUESTION,
  CUSTOM_RUN_CODE,
  DELETE_CODING_QUESTION_URL,
  FETCH_QUESTION_BY_ID,
  GET_ALL_CATEGORY,
  GET_ALL_CODING_QUESTION_URL,
  GET_ALL_LANGUAGE_URL,
  GET_CODING_QUESTION_URL,
  GET_SKILL_REPORT,
  GET_SKILL_RESULT,
  MAP_CODING_QUESTION,
  QUESTION_FILTER_BY_CATEGORY,
  QUESTION_FILTER_BY_LANGUAGE,
  QUESTION_FILTER_BY_LEVEL,
  REFERENCE_DOCUMENT_URL,
  RUN_CODE,
  SKILL_BASE_URL,
  SUBMIT_CODE,
  UPDATE_CODING_QUESTION_URL,
};
