export const ActionTypes = {
  //learning assessment actions
  GET_ALL_LEARNING_ASSESSMENT_QUESTIONS:
    "GET_ALL_LEARNING_ASSESSMENT_QUESTIONS",
  DELETE_LEARNING_ASSESSMENT_QUESTIONS: "DELETE_LEARNING_ASSESSMENT_QUESTIONS",
  DISABLE_LEARNING_ASSESSMENT_QUESTIONS:
    "DISABLE_LEARNING_ASSESSMENT_QUESTIONS",
  FETCH_TOPICS_SUCCESS: "FETCH_TOPICS_SUCCESS",

  //learning assessment moodle engine
  LOAD_QUESTIONS: "LOAD_QUESTIONS",
  ANSWER_QUESTION: "ANSWER_QUESTION",
  CLEAR_ANSWER: "CLEAR_ANSWER",
  TOGGLE_FLAG: "TOGGLE_FLAG",
  NEXT_QUESTION: "NEXT_QUESTION",
  PREVIOUS_QUESTION: "PREVIOUS_QUESTION",
  SET_QUIZ_COMPLETED: "SET_QUIZ_COMPLETED",
  ANSWER_MULTI_QUESTION: "ANSWER_MULTI_QUESTION",
  RESET_QUIZ: "RESET_QUIZ",
  SET_CURRENT_QUESTION_INDEX: "SET_CURRENT_QUESTION_INDEX",
  SET_MAX_INDEX: "SET_MAX_INDEX",

  SET_ASSESSMENT_DURATION_MINUTES: "SET_ASSESSMENT_DURATION_MINUTES",
  LEARNING_ASSESSMENT_DATE: "LEARNING_ASSESSMENT_DATE",
  LEARNING_ASSESSMENT_START_TIME: "LEARNING_ASSESSMENT_START_TIME",

  UPDATE_TIME_LEFT: "UPDATE_TIME_LEFT",

};
