# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detect.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65tect.proto\x12\x06\x64\x65tect\"\x19\n\nsumRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1a\n\x0bsumResponse\x12\x0b\n\x03num\x18\x01 \x01(\x03\x32\x46\n\x06\x44\x65tect\x12<\n\x0ftestProtoDetect\x12\x12.detect.sumRequest\x1a\x13.detect.sumResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMREQUEST']._serialized_start=24
  _globals['_SUMREQUEST']._serialized_end=49
  _globals['_SUMRESPONSE']._serialized_start=51
  _globals['_SUMRESPONSE']._serialized_end=77
  _globals['_DETECT']._serialized_start=79
  _globals['_DETECT']._serialized_end=149
# @@protoc_insertion_point(module_scope)
