apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: gateway
data:
  krakend.json: |
    {
      "version": 3,
      "port": 8080,
      "extra_config": {
        "telemetry/metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":9090"
        }
      },
      "endpoints": [
        {
          "endpoint": "/test",
          "method": "GET",
          "output_encoding": "no-op",
          "backend": [
            {
              "host": ["https://www.amazon.com"],
              "url_pattern": "/",
              "encoding": "no-op",          
              "method": "GET",
              "timeout": "2s"
            }
          ]
        }
      ]
    }
