sonar.projectKey=trace-timesheet-service
sonar.projectName=trace-timesheet-service
sonar.host.url=http://localhost:9000
sonar.login=sqp_187008c6d6ad5af4e799fa761a8f1d4c0f0d9c38
sonar.token=sqp_187008c6d6ad5af4e799fa761a8f1d4c0f0d9c38
sonar.sources=src
sonar.java.binaries=target