events {}
 
http {
    upstream doc_backend {
        server doc-service-1:8090;
        server doc-service-2:8090;
    }
 
    server {
        listen 80;
        location / {
        proxy_pass http://doc_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}