/*
this is a example for action where we can include 
our action types this file is going to act as file to store all our constant
*/

export const ActionTypes = {
  //Example
  SET_APPICATION_TITLE: "SET_APPICATION_TITLE",
  SET_USER_PROFILE_DETAILS: "SET_USER_PROFILE_DETAILS",
  SET_APPICATION_BATCH: "SET_APPICATION_BATCH",
  SET_USERS: "SET_USERS",

  SET_USER_FEEDBACK:"SET_FEEDBACK",

  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
  // proctoring
  INCREMENT_TAB_SWITCH: "INCREMENT_TAB_SWITCH",
  INCREMENT_COPY_PASTE: "INCREMENT_COPY_PASTE",
  SET_ALLOWED_VIOLATION: "SET_ALLOWED_VIOLATION",
  SET_PROCTORING: "SET_PROCTORING",

  //Admin - Create Assessment
  CHANGE_VALUE: "CHANGE_VALUE",
  CHANGE_ASSESSMENT: "CHANGE_ASSESSMENT",
  CHANGE_ASSESSMENT_NAME: "CHANGE_ASSESSMENT_NAME",

  //Admin - Proctor Select
  CHANGE_CAMERA_PROCTOR: "CHANGE_CAMERA_PROCTOR",
  CHANGE_AUDIO_PROCTOR: "CHANGE_AUDIO_PROCTOR",
  CHANGE_COPY_PASTE_PROCTOR: "CHANGE_COPY_PASTE_PROCTOR",
  CHANGE_TAB_SWITCH_PROCTOR: "CHANGE_TAB_SWITCH_PROCTOR",
  CHANGE_VIOLATION_COUNT: "CHANGE_VIOLATION_COUNT",

  //ADMIN - SKILL Question Pick
  CHANGE_SKILL_TOTAL_COUNT: "CHANGE_SKILL_TOTAL_COUNT",
  CHANGE_SKILL_QUESTION_LIST: "CHANGE_SKILL_QUESTION_LIST",
  DELETE_SKILL_QUESTION: "DELETE_SKILL_QUESTION",

  //ADMIN - Assessment Schedule

  CHANGE_ASSESSMENT_DATE: "CHANGE_ASSESSMENT_DATE",
  CHANGE_ASSESSMENT_TIME: "CHANGE_ASSESSMENT_DATE",
  CHANGE_ASSESSMENT_DURATION: "CHANGE_ASSESSMENT_DATE",

  //RESET ASSESSMENT STATE

  RESET_ASSESSMENT_STATE: "RESET_ASSESSMENT_STATE",
  RESET_PROCTOR_STATE: "RESET_PROCTOR_STATE",
  RESET_SKILL_QUESTION_PICK_STATE: "RESET_SKILL_QUESTION_PICK_STATE",

  //ADMIN KNOWEDGE Schedule

  CHANGE_LEVEL_TWO_TOPIC_ID: "CHANGE_LEVEL_TWO_TOPIC_ID",
  CHANGE_LEVEL_TWO_TOPIC_NAME: "CHANGE_LEVEL_TWO_TOPIC_NAME",
  CHANGE_LEVEL_TWO_SUBTOPIC_ID_LIST: "CHANGE_LEVEL_TWO_SUBTOPIC_ID_LIST",
  CHANGE_LEVEL_TWO_SUBTOPIC_NAME_LIST: "CHANGE_LEVEL_TWO_SUBTOPIC_NAME_LIST",
  CHANGE_LEVEL_TWO_TOTAL: "CHANGE_LEVEL_TWO_TOTAL",
  CHANGE_LEVEL_TWO_PASS_PERCENTAGE: "CHANGE_LEVEL_TWO_PASS_PERCENTAGE",
  CHANGE_LEVEL_TWO_SELECTED_TOTAL_QUESTION_COUNT:
    "CHANGE_LEVEL_TWO_SELECTED_TOTAL_QUESTION_COUNT",
  RESET_LEVEL_TWO: "RESET_LEVEL_TWO",

  //ADMIN FEEDBACK FORM FOR ASSESSMENT

  CHANGE_FORM_FIELDS : "CHANGE_FORM_FIELDS",
  RESET_FORM_FIELDS : "RESET_FORM_FIELDS",
  UPDATE_FIELD_ATTRIBUTE_NAME: "UPDATE_FIELD_ATTRIBUTE_NAME",
  UPDATE_FIELD_OPTION: "UPDATE_FIELD_OPTION",
  ADD_OPTION: "ADD_OPTION",
  REMOVE_OPTION: "REMOVE_OPTION",
  UPDATE_FIELD_TYPE: "UPDATE_FIELD_TYPE",
  UPDATE_VISIBILITY: "UPDATE_VISIBILITY",
  RESET_FIELD_REDUCER : "RESET_FIELD_REDUCER",
};
